version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./soc:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

